# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and TypeScript config
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies without running prepare scripts
RUN npm ci --ignore-scripts

# Copy source code
COPY src ./src

# Build the project
RUN npm run build

# Expose no ports since we communicate over stdio

# Default command to run the MCP server
CMD ["node", "build/index.js"]
